version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: brisk_postgres
    restart: always
    environment:
      POSTGRES_USER: brisk_user
      POSTGRES_PASSWORD: brisk_password
      POSTGRES_DB: brisk_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
