import { prisma } from './src/config/database';
import { listTraderSiteVisits } from './src/modules/site-visits/site-visits.service';
(async () => {
  const t = (await prisma.traderSiteVisitRequest.groupBy({ by: ['traderId'], _count: { _all: true }, orderBy: { _count: { traderId: 'desc' } } }))[0].traderId;
  const asc = await listTraderSiteVisits(t, { sortBy: 'visitDate', sortOrder: 'asc', limit: 100 }, 'ADMIN');
  const desc = await listTraderSiteVisits(t, { sortBy: 'visitDate', sortOrder: 'desc', limit: 100 }, 'ADMIN');
  const d1 = asc.items.map(i => i.visitDate); const d2 = desc.items.map(i => i.visitDate);
  const ordered = (a: (string|null)[], dir: number) => a.filter(Boolean).every((d, i, arr) => i === 0 || (dir > 0 ? arr[i-1]! <= d! : arr[i-1]! >= d!));
  console.log('ASC ', d1.join(','), ordered(d1, 1) ? 'PASS' : 'FAIL');
  console.log('DESC', d2.join(','), ordered(d2, -1) ? 'PASS' : 'FAIL');
  const pages: string[] = [];
  for (let page = 1; page <= 4; page++) pages.push(...(await listTraderSiteVisits(t, { sortBy: 'visitDate', sortOrder: 'asc', limit: 3, page }, 'ADMIN')).items.map(i => i.id));
  console.log('PAGED asc limit=3 equals full list', JSON.stringify(pages) === JSON.stringify(asc.items.map(i => i.id)) ? 'PASS' : 'FAIL', asc.meta.total);
  const range = await listTraderSiteVisits(t, { from: '2026-09-24', to: '2026-09-25', limit: 100 }, 'ADMIN');
  console.log('RANGE 24-25 Sep', range.items.map(i => i.visitDate).join(','), range.items.every(i => i.visitDate! >= '2026-09-24' && i.visitDate! <= '2026-09-25') ? 'PASS' : 'FAIL', 'summary', JSON.stringify(range.summary));
  const all = await listTraderSiteVisits(t, { limit: 100 }, 'ADMIN');
  const expRange = all.items.filter(i => i.visitDate && i.visitDate >= '2026-09-24' && i.visitDate <= '2026-09-25').length;
  console.log('RANGE count equals displayed-date count', range.meta.total === expRange ? 'PASS' : 'FAIL', range.meta.total, expRange);
  const sorted = await listTraderSiteVisits(t, { sortBy: 'visitDate', sortOrder: 'asc', group: 'VISITED', search: 'JOB', limit: 100 }, 'ADMIN');
  console.log('SORT+group+search', sorted.items.every(i => i.group === 'VISITED') && ordered(sorted.items.map(i => i.visitDate), 1) ? 'PASS' : 'FAIL', sorted.meta.total);
  await prisma.$disconnect();
})().catch(e => { console.error(e); process.exit(1); });
