import PDFDocument from 'pdfkit';

export type InvoicePdfInput = {
  invoiceNumber: string;
  jobRef: string | null;
  title: string;
  completedAt: Date | null;
  customerName: string;
  address: string;
  currencyCode?: string;
  lines: {
    label: string;
    amount: number;
  }[];
  totalAmount: number;
  paymentStatus: string;
};

const moneyLabel = (amount: number, currencyCode = 'EUR') => {
  const symbol = currencyCode === 'GBP' ? '£' : '€';
  return `${symbol}${amount.toFixed(2)}`;
};

/** Build a BRISK job invoice PDF buffer. */
export const buildInvoicePdfBuffer = (input: InvoicePdfInput): Promise<Buffer> =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const currency = input.currencyCode || 'EUR';

    doc.fontSize(20).text('BRISK Invoice', { align: 'left' });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#555555').text('Making Things Quicker');
    doc.fillColor('#000000');
    doc.moveDown();

    doc.fontSize(12).text(`Invoice: ${input.invoiceNumber}`);
    if (input.jobRef) doc.text(`Job Ref: ${input.jobRef}`);
    doc.text(`Job: ${input.title}`);
    doc.text(`Customer: ${input.customerName}`);
    doc.text(`Address: ${input.address || '—'}`);
    if (input.completedAt) {
      doc.text(`Completed: ${input.completedAt.toISOString().slice(0, 10)}`);
    }
    doc.text(`Payment status: ${input.paymentStatus}`);
    doc.moveDown();

    doc.fontSize(13).text('Payment summary', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11);

    for (const line of input.lines) {
      const y = doc.y;
      doc.text(line.label, 50, y, { width: 350, continued: false });
      doc.text(moneyLabel(line.amount, currency), 400, y, { width: 120, align: 'right' });
      doc.moveDown(0.35);
    }

    doc.moveDown(0.5);
    doc.fontSize(13).text(`Total: ${moneyLabel(input.totalAmount, currency)}`, {
      align: 'right',
    });

    doc.moveDown(2);
    doc.fontSize(9).fillColor('#777777').text('Generated by BRISK. This document is for your records.');
    doc.end();
  });
